ALTER TABLE agreements ADD COLUMN IF NOT EXISTS client_signature TEXT;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS admin_signature TEXT;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS client_signed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE agreements ADD COLUMN IF NOT EXISTS admin_signed_at TIMESTAMP WITH TIME ZONE;
